name: 里程碑请求
description: 使用这个模板创建议题,从而请求维护者创建里程碑
labels: ["Milestone"]
title: "Milestone: <Title>"
assignees:
  - Morsiusiurandum
body:
  - type: markdown
    attributes:
      value: |
        请将议题标题中的<Title>字段更换为你想要创建的里程碑

  - type: dropdown
    attributes:
      label: Type
      description: 你想要对里程碑做什么?
      multiple: false
      options:
        - 创建  (以当前标题创建一个新的里程碑)
        - 修改  (使用以下信息更新当前标题对应的里程碑)
        - 删除  (删除当前标题对应的里程碑,不推荐🥲)
    validations:
      required: true

  - type: input
    id: Title
    attributes:
      label: Title
      description: 里程碑标题
      placeholder: Title
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Due date (optional)
      description: 里程碑截止日期
      placeholder: 1919/08/10

  - type: textarea
    id: description
    attributes:
      label: Description
      description: 对里程碑的描述
    validations:
      required: false
