name: 跟踪任务
description: 使用这个议题模板来跟踪任务
title: "[Type]: <Title>"
body:
  - type: markdown
    attributes:
      value: |
        请将标题中的[Type]部分改为相应的Commit类型(首字母大写),<Title>部分改为议题的标题

  - type: input
    id: short-description
    attributes:
      label: 简述
      description: 简短的描述情况
      placeholder: ​逸一时,误一​世
    validations:
      required: true

  - type: textarea
    id: todo-list
    attributes:
      label: 任务列表
      description: 可在此处用Markdown语法自由编写,建议使用示例语法来拆分为更加细致的任务。拆分后的任务可轻松转换为新的议题.
      placeholder: |
        - [ ] 使用四元数硬编码旋转
        - [ ] 对控制器暴露接口
    validations:
      required: false
