name: Tracking feature
description: Use this template for tracking new features.
title: "[Feature]: <title> "
labels: ["enhancement"]
projects: ["Moon"]
body:
  - type: markdown
    attributes:
      value: |
        这个模版用来跟踪一个新功能
  - type: input
    id: short-description
    attributes:
      label: 功能简述
      description: 简短的描述功能情况
      placeholder: 例如：为角色添加转身逻辑
    validations:
      required: true
  - type: textarea
    id: todo-list
    attributes:
      label: 实现方案
      description: 简述实现思路，如没有成熟想法，可以暂空
      placeholder: |
        1. 使用四元数硬编码旋转
        2. 对控制器暴露接口  
      value: "暂无思路，待添加"
    validations:
      required: false
