name: Help Docs

on:
  workflow_run:
    workflows: [Unit Test]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository_owner == 'fictional-vision' && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') }}
    name: Create docs
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2022.3.10f1-linux-il2cpp-2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: moon-dev/Library
          key: Library-Moon
          restore-keys: |
            Library-

      - name: Unity Activation    
        run : unity-editor -batchmode -nographics -quit -serial ${{ secrets.UNITY_SERIAL }} -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} -projectPath moon-dev

      - name: Generate .csproj
        run : unity-editor -batchmode -nographics -quit -projectPath moon-dev -executeMethod Packages.Rider.Editor.RiderScriptEditor.SyncSolution
      
      - name: Return License 
        run: unity-editor -quit -batchmode -returnlicense -username ${{ secrets.UNITY_EMAIL }} -password ${{ secrets.UNITY_PASSWORD }} 

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Setup Docfx
        run: dotnet tool update docfx --tool-path ./
      
      - name: Build Site
        run: ./docfx docs/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: docs/_site
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

      # Download the generated documentation
    - name: Download site artifact
      uses: actions/download-artifact@v1
      with:
        name: _site     

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
        projectName: moon-manual
        directory: ./
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        workingDirectory: ./_site
        wranglerVersion: '3'