name: Meta Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  meta-check:
    name: "Check all .meta"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check all .meta
        uses: DeNA/unity-meta-check@v3
        with:
          target_path: moon-dev/Assets


