name: Meta Check

on:
  pull_request_target:
    paths: [moon-dev/Assets/**]
  workflow_dispatch:

jobs:
  meta-check:
    name: "Check all .meta"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check all .meta
        uses: DeNA/unity-meta-check@v3
        with:
          target_path: moon-dev/Assets
          enable_junit: true
          junit_xml_path: junit.xml

      - name: Report  
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: junit.xml
        if: always()


