name: Meta Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  meta-check:
    name: "Check all .meta"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check all .meta is comitted
        uses: Cysharp/Actions/.github/actions/check-metas@main # check meta files
        with:
          directory: moon-dev/Assets
