name: Meta Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  meta-check:
    name: "Check all .meta"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check all .meta
        uses: DeNA/unity-meta-check@v3
        with:
          target_path: moon-dev/Assets
          enable_junit: true
          junit_xml_path: junit.xml
        env:
          GITHUB_TOKEN: "${{ secrets.YOUR_GITHUB_TOKEN }}"

      - name: Report  
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: junit.xml
        if: always()


