name: Unit Test

on:
  pull_request_target:
    branches: [main]
    types: [closed]
    paths: ['moon-dev/**']
  workflow_dispatch:

jobs:
  unit-test:
    if: ${{ github.repository_owner == 'fictional-vision' && (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: moon-dev/Library
          key: Library-Moon
          restore-keys: |
            Library-

      - name: Unit test
        id: Tests 
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: moon-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}