name: Unit Test

on:
  pull_request_target:
    branches: [main]
    types: [closed]
    paths: ['moon-dev/**.cs']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Test:
    if: ${{ github.event.pull_request.merged == true || github.event.action == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      - name: Unit test
        id: Tests 
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: moon-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
