name: Unit Test

on:
  pull_request:
  push:
    branches: [main]
    paths: ['moon-dev/**']
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  Test:
    if: github.repository_owner == 'fictional-vision'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v3

      - name: Unit test
        id: Tests 
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: moon-dev/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'

      - name: Upload Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.Tests.outputs.coveragePath }}